using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DataHandlingLayer.DataModel.Enums
{
    public enum PushType
    {
        ANNOUNCEMENT_NEW, ANNOUNCEMENT_DELETED, CHANNEL_CHANGED, CHANNEL_DELETED, MODERATOR_ADDED, MODERATOR_CHANGED,
        MODERATOR_REMOVED, GROUP_DELETED, GROUP_CHANGED, PARTICIPANT_NEW, PARTICIPANT_LEFT, PARTICIPANT_REMOVED,
        PARTICIPANT_CHANGED, CONVERSATION_NEW, CONVERSATION_CHANGED, CONVERSATION_CHANGED_ALL, CONVERSATION_CLOSED,
        CONVERSATION_DELETED, CONVERSATION_MESSAGE_NEW, BALLOT_NEW, BALLOT_CHANGED, BALLOT_CHANGED_ALL,
        BALLOT_OPTION_NEW, BALLOT_OPTION_ALL, BALLOT_OPTION_DELETED, BALLOT_OPTION_VOTE, BALLOT_OPTION_VOTE_ALL,
        BALLOT_CLOSED, BALLOT_DELETED, USER_CHANGED
    }
}
